name: build_appimage
on:
  workflow_dispatch: ~
  push:
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3.1.2
      with:
        python-version: 3.9
        cache: pip
        cache-dependency-path: setup.cfg
    - name: Cache
      uses: actions/cache@v3.0.2
      with:
        path: |
          $RUNNER_TEMP/.pyoxidizer_cache
          standalone_build/appimagetool
        key: pyoxidizer_build_env_cache
    - name: install dependencies
      run: pip install .[binary_build]
    - name: build Appimage
      run: PYOXIDIZER_CACHE_DIR=$RUNNER_TEMP/.pyoxidizer_cache make -C standalone_build
    - name: test appimage
      run: standalone_build/Padrick-x86_64.AppImage validate sample_padframe.yaml

    # Generate release notes and upload asset if we pushed a release tag
    - name: generate release notes
      run: python3 update_changelog.py CHANGELOG.rst ${{github.ref_name}} > release_info.txt
      if: startsWith(github.ref, 'refs/tags/v')
    - name: create release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/v')
      with:
        files: standalone_build/Padrick-x86_64.AppImage
        name: v${{github.ref_name}}
        body_path: release_info.txt
        draft: True
