name: build_appimage
on:
  release:
    types: [released]
  workflow_dispatch: ~
  push:
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3.1.2
      with:
        python-version: 3.9
        cache: pip
        cache-dependency-path: setup.cfg
    - name: Cache
      uses: actions/cache@v3.0.2
      with:
        path: |
          $RUNNER_TEMP/.pyoxidizer_cache
          standalone_build/appimagetool
        key: pyoxidizer_build_env_cache
    - name: install dependencies
      run: pip install .[binary_build]
    - name: build Appimage
      run: PYOXIDIZER_CACHE_DIR=$RUNNER_TEMP/.pyoxidizer_cache make -C standalone_build
    - name: upload Appimage
      uses: actions/upload-artifact@v3.0.0
      with:
        name: Padrick-x86_64-${{github.ref_name}}-${{github.sha}}.AppImage
        path: standalone_build/Padrick-x86_64.AppImage
        if-no-files-found: error
